### ISSUE TITLE
cwltool - Diamond

### ISSUE THREAD

**Issue by jra001k** [hmenager/workflow-is-cwl#3]
```
$ cwl-runner Diamon.blastx-v0.9.21.cwl Diamon.blastx-v0.9.21.test.job.yaml 

[job Diamon.blastx-v0.9.21.cwl] completed success
{
    "matches": {
        "format": "http://edamontology.org/format_2333", 
        "checksum": "sha1$021f319cc66ca5c34211992209d88ed84b247ce6", 
        "basename": "test_transcripts.fasta.diamond_matches", 
        "location": "file:///home/jraciazek/snapshot/workflow-is-cwl_herve/tools/Diamond/test_transcripts.fasta.diamond_matches", 
        "path": "/home/jraciazek/snapshot/workflow-is-cwl_herve/tools/Diamond/test_transcripts.fasta.diamond_matches", 
        "class": "File", 
        "size": 12519
    }
}
Final process status is success
```

```
$ cwl-runner --debug Diamon.makedb-v0.9.21.cwl Diamon.makedb-v0.9.21.test.job.yaml 

Traceback (most recent call last):
  File "/home/jraciazek/.local/lib/python2.7/site-packages/cwltool/main.py", line 602, in main
    **vars(args))
  File "/home/jraciazek/.local/lib/python2.7/site-packages/cwltool/executors.py", line 31, in __call__
    return self.execute(*args, **kwargs)
  File "/home/jraciazek/.local/lib/python2.7/site-packages/cwltool/executors.py", line 72, in execute
    self.run_jobs(t, job_order_object, logger, **kwargs)
  File "/home/jraciazek/.local/lib/python2.7/site-packages/cwltool/executors.py", line 101, in run_jobs
    for r in jobiter:
  File "/home/jraciazek/.local/lib/python2.7/site-packages/cwltool/command_line_tool.py", line 341, in job
    builder = self._init_job(job_order, **kwargs)
  File "/home/jraciazek/.local/lib/python2.7/site-packages/cwltool/process.py", line 626, in _init_job
    builder.bindings.extend(builder.bind_input(self.inputs_record_schema, builder.job, discover_secondaryFiles=kwargs.get("toplevel")))
  File "/home/jraciazek/.local/lib/python2.7/site-packages/cwltool/builder.py", line 182, in bind_input
    bindings.extend(self.bind_input(f, datum[f["name"]], lead_pos=lead_pos, tail_pos=f["name"], discover_secondaryFiles=discover_secondaryFiles))
  File "/home/jraciazek/.local/lib/python2.7/site-packages/cwltool/builder.py", line 242, in bind_input
    raise WorkflowException("Expected value of '%s' to have format %s but\n  %s" % (schema["name"], schema["format"], ve))
WorkflowException: Expected value of 'inputRefDBFile' to have format http://edamontology.org/format_1929 but
  File has no 'format' defined: {
    "class": "File", 
    "location": "file:///home/jraciazek/snapshot/workflow-is-cwl_herve/tools/Diamond/test-input/uniref90_subset.fasta", 
    "size": 4752, 
    "basename": "uniref90_subset.fasta", 
    "nameroot": "uniref90_subset", 
    "nameext": ".fasta"
}
```
[uniref90_subset.fasta.zip](https://github.com/hmenager/workflow-is-cwl/files/2204475/uniref90_subset.fasta.zip)

**Comment by hmenager** [comment]
EDAM formats problem all solved with bf66251aac43e9982b9f1e9e7210736ba48517eb

**Comment by hmenager** [comment]
There is a remaining problem at the execution of Diamond:

```bash
$ cwltool --no-read-only ../Diamon.makedb-v0.9.21.cwl ../Diamon.makedb-v0.9.21.test.job.yaml 
/home/hmenager/galaxycwl/newcwltool/bin/cwltool 1.0.20180711112827
Resolved '../Diamon.makedb-v0.9.21.cwl' to 'file:///home/hmenager/galaxycwl/workflow-is-cwl/tools/Diamond/Diamon.makedb-v0.9.21.cwl'
/home/hmenager/galaxycwl/newcwltool/local/lib/python2.7/site-packages/rdflib/plugins/parsers/structureddata.py:30: UserWarning: html5lib not found! RDFa and Microdata parsers will not be available.
  'parsers will not be available.')
Could not load extension schema https://schema.org/docs/schema_org_rdfa.html: html5lib is not installed, cannot use RDFa and Microdata parsers.
../Diamon.makedb-v0.9.21.cwl:1:1: unrecognized extension field `http://schema.org/copyrightHolder`.  Did you include a $schemas section?
foreign properties set([u'http://edamontology.org/is_identifier_of', u'http://edamontology.org/is_topic_of', u'http://purl.obolibrary.org/obo/edam#obsolete', u'http://edamontology.org/has_output', u'http://edamontology.org/has_topic', u'http://purl.obolibrary.org/obo/edam#operations', u'http://purl.obolibrary.org/obo/edam#edam', u'http://purl.obolibrary.org/obo/edam#topics', u'http://edamontology.org/is_input_of', u'http://edamontology.org/has_identifier', u'http://edamontology.org/is_function_of', u'http://edamontology.org/is_output_of', u'http://edamontology.org/is_format_of', u'http://edamontology.org/has_function', u'http://www.geneontology.org/formats/oboInOwl#SubsetProperty', u'http://edamontology.org/has_format', u'http://purl.obolibrary.org/obo/edam#identifiers', u'http://purl.obolibrary.org/obo/edam#data', u'http://purl.obolibrary.org/obo/edam#events', u'http://edamontology.org/has_input', u'http://purl.obolibrary.org/obo/edam#formats'])
../Diamon.makedb-v0.9.21.cwl:1:1: unrecognized extension field `http://schema.org/license`.  Did you include a $schemas section?
foreign properties set([u'http://edamontology.org/is_identifier_of', u'http://edamontology.org/is_topic_of', u'http://purl.obolibrary.org/obo/edam#obsolete', u'http://edamontology.org/has_output', u'http://edamontology.org/has_topic', u'http://purl.obolibrary.org/obo/edam#operations', u'http://purl.obolibrary.org/obo/edam#edam', u'http://purl.obolibrary.org/obo/edam#topics', u'http://edamontology.org/is_input_of', u'http://edamontology.org/has_identifier', u'http://edamontology.org/is_function_of', u'http://edamontology.org/is_output_of', u'http://edamontology.org/is_format_of', u'http://edamontology.org/has_function', u'http://www.geneontology.org/formats/oboInOwl#SubsetProperty', u'http://edamontology.org/has_format', u'http://purl.obolibrary.org/obo/edam#identifiers', u'http://purl.obolibrary.org/obo/edam#data', u'http://purl.obolibrary.org/obo/edam#events', u'http://edamontology.org/has_input', u'http://purl.obolibrary.org/obo/edam#formats'])
../Diamon.makedb-v0.9.21.cwl:1:1: unrecognized extension field `https://www.sevenbridges.comwrapperAuthor`.  Did you include a $schemas section?
foreign properties set([u'http://edamontology.org/is_identifier_of', u'http://edamontology.org/is_topic_of', u'http://purl.obolibrary.org/obo/edam#obsolete', u'http://edamontology.org/has_output', u'http://edamontology.org/has_topic', u'http://purl.obolibrary.org/obo/edam#operations', u'http://purl.obolibrary.org/obo/edam#edam', u'http://purl.obolibrary.org/obo/edam#topics', u'http://edamontology.org/is_input_of', u'http://edamontology.org/has_identifier', u'http://edamontology.org/is_function_of', u'http://edamontology.org/is_output_of', u'http://edamontology.org/is_format_of', u'http://edamontology.org/has_function', u'http://www.geneontology.org/formats/oboInOwl#SubsetProperty', u'http://edamontology.org/has_format', u'http://purl.obolibrary.org/obo/edam#identifiers', u'http://purl.obolibrary.org/obo/edam#data', u'http://purl.obolibrary.org/obo/edam#events', u'http://edamontology.org/has_input', u'http://purl.obolibrary.org/obo/edam#formats'])
[job Diamon.makedb-v0.9.21.cwl] /tmp/tmpYv4Dgi$ docker \
    run \
    -i \
    --volume=/tmp/tmpYv4Dgi:/var/spool/cwl:rw \
    --volume=/tmp/tmptjTtbw:/tmp:rw \
    --volume=/home/hmenager/galaxycwl/workflow-is-cwl/tools/Diamond/test-input/uniref90_subset.dmnd:/var/lib/cwl/stg7b4e0817-603c-476a-941b-e232191d6de8/uniref90_subset.dmnd:ro \
    --volume=/home/hmenager/galaxycwl/workflow-is-cwl/tools/Diamond/test-input/uniref90_subset.fasta:/var/lib/cwl/stg9ec99aeb-5706-4287-a14d-8ba8b7cf69f7/uniref90_subset.fasta:ro \
    --workdir=/var/spool/cwl \
    --user=1000:1000 \
    --rm \
    --env=TMPDIR=/tmp \
    --env=HOME=/var/spool/cwl \
    --memory=1024m \
    buchfink/diamond:version0.9.21 \
    diamond \
    makedb \
    --in \
    /var/lib/cwl/stg9ec99aeb-5706-4287-a14d-8ba8b7cf69f7/uniref90_subset.fasta \
    --db \
    /var/lib/cwl/stg7b4e0817-603c-476a-941b-e232191d6de8/uniref90_subset.dmnd
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
diamond v0.9.21.122 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU AGPL <https://www.gnu.org/licenses/agpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 4
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Database file: /var/lib/cwl/stg9ec99aeb-5706-4287-a14d-8ba8b7cf69f7/uniref90_subset.fasta
Opening the database file... Read-only file system
 [0.003566s]
Error: Error opening file /var/lib/cwl/stg7b4e0817-603c-476a-941b-e232191d6de8/uniref90_subset.dmnd
[job Diamon.makedb-v0.9.21.cwl] Job error:
Error collecting output for parameter 'diamondDatabaseFile':
../Diamon.makedb-v0.9.21.cwl:70:7: Did not find output file with glob pattern: '['uniref90_subset*']'
[job Diamon.makedb-v0.9.21.cwl] completed permanentFail
{}
Final process status is permanentFail
```

**Comment by mscheremetjew** [comment]
This should be fixed now. If you pull my latest changes in.

**Comment by jra001k** [comment]
```
cwl-runner --debug Diamon.makedb-v0.9.21.cwl Diamon.makedb-v0.9.21.test.job.yaml 
```
