### ISSUE TITLE
sync201811 - galaxy+cwltool - Diamond

### ISSUE THREAD

**Issue by jra001k** [hmenager/workflow-is-cwl#30]
Add Tool link in tools_conf.xml
```
<tool file="../../workflow-is-cwl/tools/Diamond/Diamon.makedb-v0.9.21.cwl" />
```

When running the tool, error below occurs

```
/home/jra001k/snapshot/galaxy/database/jobs_directory/000/12/tool_script.sh: line 10: diamond: command not found
Traceback (most recent call last):
  File "/home/jra001k/snapshot/galaxy/database/jobs_directory/000/12/relocate_dynamic_outputs.py", line 1, in <module>
    from galaxy_ext.cwl.handle_outputs import relocate_dynamic_outputs; relocate_dynamic_outputs()
  File "/home/jra001k/snapshot/galaxy/lib/galaxy_ext/cwl/handle_outputs.py", line 21, in relocate_dynamic_outputs
    handle_outputs()
  File "/home/jra001k/snapshot/galaxy/lib/galaxy/tools/cwl/runtime_actions.py", line 117, in handle_outputs
    outputs = job_proxy.collect_outputs(tool_working_directory)
  File "/home/jra001k/snapshot/galaxy/lib/galaxy/tools/cwl/parser.py", line 578, in collect_outputs
    return self.cwl_job().collect_outputs(tool_working_directory)
  File "/home/jra001k/snapshot/galaxy/.venv/local/lib/python2.7/site-packages/cwltool/command_line_tool.py", line 539, in collect_output_ports
    compute_checksum=compute_checksum)
  File "/home/jra001k/snapshot/galaxy/.venv/local/lib/python2.7/site-packages/schema_salad/sourceline.py", line 168, in __exit__
    raise self.makeError(six.text_type(exc_value))
cwltool.errors.WorkflowException: Error collecting output for parameter 'diamondDatabaseFile':
:1:1: Did not find output file with glob pattern: '['uniref90_subset.dmnd']'
]
```

**Comment by jra001k** [comment]
Fixed, this error was because docker configuration was not set in job_conf.xml file.

The tool now run successfully in Galaxy.
